// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2p3KXdE3yTFywoFAlp_oBgDCtuki3f3U',
    appId: '1:41285215541:web:976c0b7b9e615e1c8d987c',
    messagingSenderId: '41285215541',
    projectId: 'nutritrack-b3f5f',
    authDomain: 'nutritrack-b3f5f.firebaseapp.com',
    storageBucket: 'nutritrack-b3f5f.firebasestorage.app',
    measurementId: 'G-5R3MSJDYQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF-ZPkLgGku4lmlcJzKUHXVHgN4ZyoJTw',
    appId: '1:41285215541:android:e4f35ca04142d4028d987c',
    messagingSenderId: '41285215541',
    projectId: 'nutritrack-b3f5f',
    storageBucket: 'nutritrack-b3f5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM8QdLdUkydfD1R_gdveiolSP-LvLTbpM',
    appId: '1:41285215541:ios:8a5e65f8f10c46f28d987c',
    messagingSenderId: '41285215541',
    projectId: 'nutritrack-b3f5f',
    storageBucket: 'nutritrack-b3f5f.firebasestorage.app',
    iosBundleId: 'com.example.nutritrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM8QdLdUkydfD1R_gdveiolSP-LvLTbpM',
    appId: '1:41285215541:ios:8a5e65f8f10c46f28d987c',
    messagingSenderId: '41285215541',
    projectId: 'nutritrack-b3f5f',
    storageBucket: 'nutritrack-b3f5f.firebasestorage.app',
    iosBundleId: 'com.example.nutritrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2p3KXdE3yTFywoFAlp_oBgDCtuki3f3U',
    appId: '1:41285215541:web:c72a44fe40ab48208d987c',
    messagingSenderId: '41285215541',
    projectId: 'nutritrack-b3f5f',
    authDomain: 'nutritrack-b3f5f.firebaseapp.com',
    storageBucket: 'nutritrack-b3f5f.firebasestorage.app',
    measurementId: 'G-VBZ549PDM7',
  );
}
